# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
kotlin.code.style=official

# Disable built-in Kotlin in AGP 9+
android.builtInKotlin=false
android.newDsl=false
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE

# Use K1 frontend for KSP processor stability with Room & Hilt
ksp.useK2=false
